version: 2.1

jobs:

  build_macos:
    macos:
      xcode: "10.0.0"
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
      - run: security default-keychain -s build.keychain
      - run: security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
      - run: echo $KEYSTORE | base64 --decode - > keystore.p12
      - run: security import keystore.p12 -k build.keychain -P $KEYCHAIN_PASSWORD -T /usr/bin/codesign
      - run: yarn electron-builder --publish always --mac


  build_windows:
    docker:
      - image: electronuserland/builder:wine
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn electron-builder --publish always --win

  build_web:
    working_directory: ~/repo
    
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build App
          command: yarn build

workflows:
  build:
    jobs:
      - build_web
      - build_macos
      - build_windows